#!/usr/bin/env bash 
CLEAR="\033[0m"
ORANGE="\033[33m"

successfully() {
  $* || (echo "failed" 1>&2 && exit 1)
}

fancy_echo() {
  echo -e ${ORANGE}$1${CLEAR}
  echo
}

if lsb_release -c | grep -qEv 'precise|quantal|wheezy|raring'
then
  fancy_echo "Sorry! we don't currently support that distro."
  exit 1;
fi

fancy_echo "adding ppas for java and git"
  succdessfully sudo add-apt-repository -y ppa:webupd8team/java
  succdessfully sudo add-apt-repository -y ppa:git-core/ppa

fancy_echo "looking for aptitude..."
  if command -v aptitude >/dev/null; then
    fancy_echo "Using aptitude ..."
  else
    fancy_echo "Installing aptitude ..."
    successfully sudo apt-get install -y aptitude
  fi

fancy_echo "updating the system..."  
  successfully sudo aptitude update
  successfully sudo aptitude -y full-upgrade

fancy_echo "Installing common libraries ..."
  successfully sudo aptitude install -y alacarte apache2 apache2-prefork-dev autoconf automake bash bison build-essential clamav clamav-freshclam compizconfig-settings-manager configure-trackpoint curl dconf-tools git ia32-libs libc6-dev libcurl4-openssl-dev libffi-dev libgdbm-dev libgnome2-0:i386 libgnomeprint2.2-0:i386 libgnomeprintui2.2-0:i386 libgnomeui-0:i386 libgnomevfs2-bin:i386 libjpeg62:i386 libksba-dev libksba8 libqtwebkit-dev libreadline6 libreadline6-dev libsqlite3-dev libssl-dev libtool libxml2-dev libxslt-dev libxslt1-dev libyaml-dev meld mysql-client mysql-server ncpfs ncurses-dev openssl oracle-java7-installer patch php5 php5-cli php5-curl php5-mysql php5-xdebug php5-xsl php5-intl php5-dev pkg-config pwgen qgit sqlite3 subversion terminator ttf-mscorefonts-installer vim vim-gtk tmux exuberant-ctags zlib1g zlib1g-dev postgresql postgresql-server-dev-all redis-server imagemagick watch dkms gnome-tweak-tools

#fancy_echo "Installing The Silver Searcher (better than ack or grep) to search the contents of files ..."
#  successfully git clone git://github.com/ggreer/the_silver_searcher.git /tmp/the_silver_searcher
#  successfully sudo aptitude install -y automake pkg-config libpcre3-dev zlib1g-dev
#  successfully sh /tmp/the_silver_searcher/build.sh
#  successfully cd /tmp/the_silver_searcher
#  successfully sh build.sh
#  successfully sudo make install
#  successfully cd ~
#  successfully rm -rf /tmp/the_silver_searcher

fancy_echo "Installing rvm..."
  successfully curl -L https://get.rvm.io | bash -s stable --rails
  successfully source ~/.rvm/scripts/rvm

fancy_echo "Updating to latest Rubygems version ..."
  successfully gem update --system

fancy_echo "Installing critical Ruby gems for Rails development ..."
  successfully gem install bundler foreman pg rails thin --no-document

fancy_echo "Installing GitHub CLI client ..."
  successfully gem install hub --no-document

fancy_echo "Installing Heroku CLI client ..."
  successfully wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh

fancy_echo "Installing the heroku-config plugin to pull config variables locally to be used as ENV variables ..."
  successfully heroku plugins:install git://github.com/ddollar/heroku-config.git
